version: '3.8'

services:
  frontend:
    build:
      context: . 
      dockerfile: Dockerfile  
    container_name: frontend
    ports:
      - "5173:5173"  # Vite 개발 서버 포트
    expose:
      - "5173"
    environment:
      - NODE_ENV=development
    restart: always

  nginx:
    build:
      context: ./nginx  # nginx 폴더를 컨텍스트로 지정
      dockerfile: Dockerfile  # nginx 폴더의 Dockerfile 사용
    container_name: nginx
    ports:
      - "80:80"  # Nginx 기본 HTTP 포트
    depends_on:
      - frontend
    restart: always
